# Generated by Django 4.1.7 on 2023-04-03 08:36

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='comment',
            field=django_summernote.fields.SummernoteTextField(verbose_name='コメント'),
        ),
    ]
