# Generated by Django 4.1.7 on 2023-04-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_alter_topic_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='comment',
            field=models.TextField(verbose_name='コメント'),
        ),
    ]
